#!/bin/perl
use strict;
use warnings;
use File::Basename;

my $HOME     = glob("~");
my $LOGS_DIR = "/tmp/river_logs";

mkdir $LOGS_DIR;
die "Error creating logs directory: $!\n" unless $!{EEXIST};

open STDOUT, '>', "$LOGS_DIR/init.log" or die "error redirecting STDOUT to logfile: $!";
open STDERR, '>&STDOUT' or die "Can't dup STDOUT: $!";

sub daemon {
    my ($program, @args) = @_;
    print "Spawning daemon: $program\n";
    if (!(my $pid = fork)) {
        basename($program);
        open STDOUT, ">", "$LOGS_DIR/${\( basename($program) )}.log" or die "error creating log file for '$program': $!";
        open STDERR, '>&STDOUT' or die "Can't dup STDOUT: $!";
        exec($program, @args);
        exit;
    }
}

daemon "/usr/bin/gpg-agent", "--server";
daemon "/usr/bin/pipewire";
daemon "$HOME/.local/share/cargo/bin/ra-multiplex-server";
daemon "/usr/bin/kanshi";
daemon "/usr/bin/swaybg", "-i", "$HOME/Pictures/wallpapers/astronaut-gruvbox.png";
daemon "/usr/bin/sandbar", qw(
    -active-fg-color    282828
    -active-bg-color    98871a
    -inactive-fg-color  fbf1c7
    -inactive-bg-color  282828
    -title-bg-color     282828
    -font Terminus:size=12
    -hide-vacant-tags
    -bottom
);

system("$HOME/.config/river/keymap.sh");
system("/usr/bin/riverctl default-layout rivercarro");

# This will block until we exit river and get sent a termination signal
system("/usr/local/bin/rivercarro", "-outer-gaps", "0", "-inner-gaps", "0");
